### ISSUE TITLE
Show all probe tags

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-dash#25]
Right now, we're only showing user tags. We should show all in the order: user, admin, and system. This will require first syncing the system/admin tags to the DB as we don't store them yet.

**Comment by alexey-yarmosh** [comment]
Currently there is no functionality for admin tags. Should that be added here?

**Comment by MartinKolarik** [comment]
There is no way to create them, but we have the prefix defined, so what I meant: show all tags and in that order. But don't add any  functionality for creating them.
