### ISSUE TITLE
/probes mobile view

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-dash#33]
Design in Figma, reuses what we have on the homepage, just adds tags + info at the bottom. Make sure the credits message at the bottom fits at 360px with five-digit numbers like `15,000`

Ignore this part, keep nav as it is:

![image](https://github.com/user-attachments/assets/62ecc1bc-1a34-4cfd-ab5a-56fa20a91f9e)

**Comment by alexey-yarmosh** [comment]
It fits like that. Should that be one line?

<img width="405" alt="image" src="https://github.com/user-attachments/assets/d28c21fd-afb8-4c20-a5ab-cd2c4e432611">

**Comment by MartinKolarik** [comment]
It's probably fine, or we can try to make the font a little smaller if that helps.
